export EztvProvider from './EztvProvider'
export MovieProvider from './MovieProvider'
export YtsProvider from './YtsProvider'
export EttvProvider from './EttvProvider'
export ZooqleProvider from './ZooqleProvider'
